# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('scriptwriter', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=100)),
                ('star', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=0, max_digits=19)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
                ('poster', models.ImageField(blank=True, upload_to='movies/%Y/%m/%d')),
                ('rank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.Category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='movie',
            index_together=set([('id', 'slug')]),
        ),
    ]
