# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
