# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
